### ISSUE TITLE
Migrate YIO-Remote/buildroot repository

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-os#1]
Migrate YIO specific files from [cloned buildroot repo](https://github.com/YIO-Remote/buildroot) and create a buildable project.

Main goals:

- [x] Use buildroot as Git submodule
- [x] Use the same buildroot release 
- [x] Use the same RPI kernel sources
  - Set remote Git tar release URL as source instead of manually downloaded local file
- [x] Build the same binary SD image as with the old project
- [ ] Create initial master commit to use dev branch for further migrations

**Comment by zehnm** [comment]
Migrated the [YIO specific commits](https://github.com/buildroot/buildroot/compare/master...YIO-Remote:master) from the [cloned buildroot repo](https://github.com/YIO-Remote/buildroot) with Git cherry picking, omitting buildroot specific merges:

    git remote add oldrepo https://github.com/YIO-Remote/buildroot.git
    git remote update
    git cherry-pick 45eeb09
    git cherry-pick 2c66c3b
    git cherry-pick fe1ce6a
    git cherry-pick ecc6bc8
    git cherry-pick 5e581b9
    git cherry-pick 744e341
    git cherry-pick 782ec50
    git cherry-pick dbfb902
    git cherry-pick 653b04a
    # merge buildroot git cherry-pick 6b12962
    git cherry-pick c68ed80
    git cherry-pick 095119a
    git cherry-pick a39898c
    git cherry-pick 6e153ce
    git cherry-pick 05fd326
    git cherry-pick 94c4d8f
    git cherry-pick 3f65cd6
    # merge PHP git cherry-pick b8c2f7e
    git cherry-pick 931a007
    git cherry-pick 457a883
    git cherry-pick 38422f4
    git cherry-pick 90e421f
    git cherry-pick 19aac87
    git cherry-pick e309537
    git cherry-pick 51a6f4d
    git cherry-pick 3c60851
    git cherry-pick 4915cca
    git cherry-pick 69618f2
    # PR3 already included git cherry-pick d254cb9
    # PR4 already included git cherry-pick 986f0f2
    git cherry-pick 2b73f06
    git cherry-pick 261c9be
    git cherry-pick 4d5744d
    git cherry-pick 85cb7f3
    git cherry-pick 6da6e50
    git push
    git remote remove oldrepo

**Comment by zehnm** [comment]
Cherry picked inital fixes of my [Wifi fixes pull request in YIO-Remote/buildroot](https://github.com/YIO-Remote/buildroot/pull/5) to have a working WiFi setup.

I've omitted the [Rewrote WiFi scanning with iw scan output parsing](https://github.com/YIO-Remote/buildroot/pull/5/commits/c8fdf63f9b47cc9a58da3ed111cce9c4d68bb2b4) part for now until someone can verify it.

**Comment by martonborzak** [comment]
It's on my todo list for the weekend!

**Comment by zehnm** [comment]
> It's on my todo list for the weekend!

Thanks! I've just merged the initial migration into develop. Once you confirm it's ok I'll merge it into master. This will then represent the state of your buildroot repo.

**Comment by martonborzak** [comment]
Great! I also want to do a test on the buildroot config, just to make sure
it compiles and can be used with Qt for cross compiling.

**Comment by zehnm** [comment]
Let me know if there are any issues. It's possible I missed something from your buildroot setup.

My milestone for this weekend is compiling the current remote app and get it running on the RPi.

**Comment by martonborzak** [comment]
Let me know if you need help with that :)

Seems like we should have a working setup this weekend.

**Comment by martonborzak** [comment]
Everything works. Cross compilation and also the generated image.
