### ISSUE TITLE
Keep web server running after reboot?

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-os#10]
Current state:

- Reboot: webserver only runs if WiFi setup hasn't been completed yet
- After WiFi setup: webserver keeps running until remote is rebooted

Question:

@nklerk  Will the webserver be used for the web-configurator or something else?

Proposed change:
- If required: change lighttpd service state to enabled
- Not required: shutdown lighttpd after WiFi setup

**Comment by martonborzak** [comment]
The web server is used for the web configurator. The lighttpd server can be started and stopped from the remote UI. It’s not always running. Just when the user wants to configure the remote

**Comment by zehnm** [comment]
As mentioned in https://github.com/YIO-Remote/remote-os/issues/18#issuecomment-544262674 the web server shall not run after reboot. I.e. keep as is and closing this issue.
