### ISSUE TITLE
Add partitions for software update

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-os#16]
- add partition to hold the original image for recovery
- add partition to hold the downloaded image for whole system update

**Comment by zehnm** [comment]
Hopefully someone can help us out here - in the meantime let's start gathering infos:

- https://mkrak.org/2018/01/10/updating-embedded-linux-devices-part1/

**Comment by zehnm** [comment]
### Possible Solution
#### Option A
- A / B root file system
- One data partition

Advantages:
- simpler setup, only system partition needs to be swapped
- No data migration during a system update
- Needs less space

Disadvantages:
- No fallback or backup if something happens to the data partition

#### Option B
- A / B root file system
- A / B data partitions

Advantages:
- Simple fallback to old state

Disadvantages:
- Data needs to be migrated during a system update
- Needs more space


#### Further options
- An additional recovery partition holding a default image, like a "factory reset" feature.
- Read only system partition with an overlay filesystem. Reset function would throw away overlay the put the system in the default state.
