### ISSUE TITLE
Wrong lighttpd configuration for web-configurator

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-os#18]
The web configuration redirect issues in #8 has been fixed in master and dev.
However, the web server configuration is inconsistend and doesn't work if WiFi has been setup by the configuration file in /boot.

@nklerk and @martonborzak How and when shall the web-configurator be accessible?

**Current behavior:**

- After WiFi setup: lighttp configuration is switch to configuration mode
  - lighttp configuration setup is active (/etc/lighttpd/lighttpd-config.conf)
  - web-configurator is accessible
  - after reboot lighttp is switched off
- WiFi configuration provided by /boot/wpa_supplicant.conf in initial boot
  - default lighttp configuration active (/etc/lighttpd/lighttpd.conf)
  - web-configurator NOT accessible. 403

**Suggested change:**

- [x] Same lighttpd configuration after access point mode or wifi-copy
- [x] Default lighttpd configuration: web-configurator

**Open questions:**

- [x] leave lighttpd running after access point setup?
- [x] start lighttpd after device reboot? See #10

**Comment by martonborzak** [comment]
@zehnm 

After wifi is configured, the web configurator should be accessible. So probably need to check if wifi is working and then copy the corresponding lighttpd conf.

I wouldn't start lighttpd after reboot to save as many resources as possible -> fluid UI. The user can turn it on and off from the settings menu.

**Comment by zehnm** [comment]
Ok, then I will fix the wifi-copy script to use the lighttpd-config configuration.

**Comment by martonborzak** [comment]
Great, thank you!

**Comment by martonborzak** [comment]
Can this issue be closed @zehnm ? :)

**Comment by zehnm** [comment]
This issue will be auto closed when the dev branch is merged into master.
I usually add the magic keywords in the commit messages that the referenced issue will be closed.

**Comment by zehnm** [comment]
This issue will be auto closed when the dev branch is merged into master.
I usually add the magic keywords in the commit messages that the referenced issue will be closed.
