### ISSUE TITLE
High cpu usage of systemd-journald

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-os#22]
In my developer image journald constantly uses around 20% CPU

    63     1 root     S    77932  20%   0% /usr/lib/systemd/systemd-journald

Assumptions:

- journald needs to configured for the slow file system
- some processes produce too many log entries.
  Journals 10min after an initial boot:

```
# ls -lah /var/log/journal/33de407d550a438b9dd25f23caf18d76/
total 61M
drwxr-sr-x    2 root     systemd-    4.0K Oct 28 20:33 .
drwxr-sr-x    4 root     systemd-    4.0K Feb 14  2019 ..
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:48 system.journal
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:33 system@1196ca2117c446808dc8df67a32609c4-0000000000000001-000581d7e395712f.journal
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:39 user-1000.journal
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:33 user-1000@3b7f731e37034dd2b4b1430f977baa13-0000000000000119-000581d7e4138088.journal
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:34 user-1002.journal
-rw-r-----    1 root     systemd-    6.1M Feb 14  2019 user-1002@efc231c617cb4ab795d19718bae1a967-000000000000013b-000581d7e41cd781.journal
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:34 user-1007.journal
-rw-r-----    1 root     root        6.1M Oct 28 20:33 user-1007@c75fdcc1c578477382842e8bb5badd25-00000000000000d8-000581d7e3b93a37.journal
-rw-r-----    1 root     systemd-    6.1M Oct 28 20:34 user-1008.journal
-rw-r-----    1 root     systemd-    6.1M Feb 14  2019 user-1008@f08417c667f649a3a61ff6834d6e7f8a-0000000000000115-000581d7e41091f0.journal
```

TODO:
- [ ] check if this only happens in the developer image or also in the regular image
- [ ] check if this is new with the 4.14.98 kernel
- [ ] verify configuration

Ressources:
- https://www.freedesktop.org/software/systemd/man/journald.conf.html
- Google for `systemd-journald high cpu usage raspberry pi`: About 341’000 results!

**Comment by zehnm** [comment]
Option: change log destination to ram. Configure `/etc/systemd/journald.conf`:

    [Journal]
    Storage=volatile

and restart journald

**Comment by martonborzak** [comment]
I haven't experienced that on the remote with the latest from this repo.

**Comment by zehnm** [comment]
Couldn't reproduce with latest images. I could also have mistaken the cpu with mem% column.
