### ISSUE TITLE
WiFi setup: WPS support required?

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-os#27]
Do we need to support WPS?
Personally I don't like WPS, have never and will never use it, nor do I have the hardware to test it.
I just want to ask your opinion if it's an expected feature for 'regular non-techie home users'.

My opinion is: won't fix & we better spend time on more important missing features.
But if it's something that many people expect we can put it in the low priority backlog...

More information on how to implement it with wpa_supplicant: [wpa_supplicant and Wi-Fi Protected Setup (WPS)](https://w1.fi/cgit/hostap/plain/wpa_supplicant/README-WPS)

**Comment by martonborzak** [comment]
I don’t think we should focus on WPS.

**Comment by zehnm** [comment]
The wifi control rewrite with direct wpa_supplicant offers WPS support.
For now we don't implement it and focus on more important features.
