### ISSUE TITLE
Update strategy for the not just the app but the whole system.

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-os#29]
Let's try to start thinking about it how to do it.

For inspiration:
https://mkrak.org/2018/01/10/updating-embedded-linux-devices-part1/

**Comment by zehnm** [comment]
Summary of our discussion, feedback from Discord and initial experiments:
- Using [SWUpdate](https://github.com/sbabic/swupdate) as system update framework
  - Optional web server allows uploading system image and triggering update
- A / B system partition setup for failsafe system updates
- U-Boot for choosing the valid system partition
  - Boot counter & setting U-Boot env variable in Linux after successful boot
  - After n failed boots: switch back to the old partition

Open issues:
- Partition layout details: #16 
  - One data partition or A / B data partitions. 
- Read only system partition: #49  
  - The initial system update feature will most likely have regular read-write system partitions.
 
Further resources:
- https://www.embedded.com/ota-updates-for-embedded-linux-part-1-fundamentals-and-implementation/
- https://afterhourscoding.wordpress.com/2020/07/26/integrating-swupdate-with-u-boot/
- https://mkrak.org/wp-content/uploads/2018/04/FOSS-NORTH_2018_Software_Updates.pdf
- https://www.slideshare.net/MenderOTA/the-ultimate-guide-to-software-updates-on-embedded-linux-devices
- https://bootlin.com/blog/building-a-linux-system-for-the-stm32mp1-remote-firmware-updates/
- https://www.embedded-software-engineering.de/automatisches-firmware-update-fuer-embedded-linux-a-833310/
