### ISSUE TITLE
manually set time

### ISSUE THREAD

**Issue by pauldogg** [YIO-Remote/remote-os#51]
I am unable to get the correct time to be displayed.

it would be nice to be able to set it manually until it can pickup the time from servers.

**Comment by zehnm** [comment]
@pauldogg you can set the time in a ssh shell with the following commands:
- Date and time:
  - Show current time: `timedatectl`  
     Note: NTP is currently not integrated in systemd, that's why it's showing n/a. But there's ntpd running which synchronizes the time.
  - Set date and time: `timedatectl set-time YYYY-MM-DD HH:MM:SS`  
     Example: `timedatectl set-time '2020-09-08 03:19:00'`
- Time zone:
  - List timezones: `timedatectl list-timezones`
  - Set timezone example: `timedatectl set-timezone America/Los_Angeles`

Does this answer your question?

There's a feature branch in progress to replace ntpd with systemd's timesyncd service and using a clock file to persist the last time before shutdown. This will greatly improve the time issues until the correct time is synchronized from a time server.
