### ISSUE TITLE
boot partition mount point: possible to change it to /boot?

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-os#6]
Is there a particular reason that the boot partition is mounted as /mnt/boot?
Besides the www copy script, are there any accesses from the remote app?

I would like to change it to the default /boot mount point. 

Reasons:

- Using other development hardware requires additional software and installation scripts, e.g. [Pimoroni's HyperPixel](https://shop.pimoroni.com/products/hyperpixel-4) which changes the /boot/config.txt file.
- It's the standard mount point :-)

**Comment by martonborzak** [comment]
The remote app looks for the config files in there. We can change it, but then we have to make sure the app is also change. There are a couple of places in the code where we need to change.

**Comment by zehnm** [comment]
Ok good to know, I haven't reached the app code yet.
I'll test with a symlink at the old location if the app is still happy (once I get it up and running) and report back.
Then we could change the app at a later time.

**Comment by martonborzak** [comment]
Alright. It’s no big deal, just has to be coordinated :)

**Comment by zehnm** [comment]
The reason I'm asking, I don't want to break (too many) things before I have a good understanding how everything works together :-)

**Comment by martonborzak** [comment]
Good approach :D

**Comment by zehnm** [comment]
Boot partition is now mounted in /boot and a symlink keeps /mnt/boot available until the app is changed.
