### ISSUE TITLE
/usr/lib/fonts can be deleted

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-os#9]
rootfs overlay/urs/lib/fonts/ can be deleted as fonts were moved to /usr/bin/yio-remote/fonts/

**Comment by zehnm** [comment]
On the built image there are no fonts in `/usr/bin/yio-remote/fonts/`.

Where are they included?

**Comment by martonborzak** [comment]
It’s not updated on that repo

**Comment by zehnm** [comment]
I also don't find it in the old buildroot repo: https://github.com/YIO-Remote/buildroot/tree/master/board/yio-remote/rpi0/rootfs_overlay/usr/bin/yio-remote

Or do I misunderstand you?
Should the fonts be included during the build or are they installed later (from the app?) at /usr/bin/yio-remote/fonts?

**Comment by martonborzak** [comment]
It was a change that was not put on the buildroot repo yet.

**Comment by zehnm** [comment]
Ok got it, I will move the files

**Comment by martonborzak** [comment]
Thanks
